export const doctors = [
  {
    id: 1,
    image: "https://randomuser.me/api/portraits/women/45.jpg",
    name: "Dr. Light Mabelane",
    specialization: "Pediatrician",
    location: "Sandton",
    services: [
      { name: "Consultation", price: 150 },
      { name: "Child Vaccination", price: 100 },
      { name: "Newborn Checkup", price: 180 },
      { name: "Growth Monitoring", price: 120 },
    ],
    phone: "+27 11 123 4567",
    experience: "15 years",
    rating: "4.7",
  },
  {
    id: 11,
    image: "https://randomuser.me/api/portraits/men/16.jpg",
    name: "Dr. Charles Ndobe",
    specialization: "Pediatrician",
    location: "Sandton",
    services: [
      { name: "Consultation", price: 150 },
      { name: "Child Vaccination", price: 100 },
      { name: "Newborn Checkup", price: 180 },
      { name: "Growth Monitoring", price: 120 },
    ],
    phone: "+27 11 123 4567",
    experience: "15 years",
    rating: "4.7",
  },
  {
    id: 2,
    image: "https://randomuser.me/api/portraits/women/44.jpg",
    name: "Dr. Jane Doe",
    specialization: "Cardiologist",
    location: "Johannesburg",
    services: [
      { name: "Cardiac Consultation", price: 200 },
      { name: "ECG", price: 250 },
      { name: "Stress Test", price: 300 },
    ],
    phone: "+27 11 987 6543",
    experience: "12 years",
    rating: "4.8",
  },
  {
    id: 3,
    image: "https://randomuser.me/api/portraits/men/46.jpg",
    name: "Dr. John Smith",
    specialization: "Dermatologist",
    location: "Cape Town",
    services: [
      { name: "Skin Consultation", price: 180 },
      { name: "Acne Treatment", price: 220 },
      { name: "Mole Removal", price: 250 },
    ],
    phone: "+27 21 765 4321",
    experience: "10 years",
    rating: "4.5",
  },
  {
    id: 4,
    image: "https://randomuser.me/api/portraits/women/47.jpg",
    name: "Dr. Emma Jones",
    specialization: "General Practitioner",
    location: "Pretoria",
    services: [
      { name: "General Consultation", price: 100 },
      { name: "Health Checkup", price: 120 },
      { name: "Flu Vaccination", price: 80 },
    ],
    phone: "+27 12 345 6789",
    experience: "8 years",
    rating: "4.6",
  },
  {
    id: 5,
    image: "https://randomuser.me/api/portraits/men/47.jpg",
    name: "Dr. Peter Parker",
    specialization: "Neurologist",
    location: "Durban",
    services: [
      { name: "Neurological Consultation", price: 250 },
      { name: "Brain Scan", price: 400 },
      { name: "Nerve Conduction Study", price: 350 },
    ],
    phone: "+27 31 234 5678",
    experience: "20 years",
    rating: "4.9",
  },
];
